# Generated by Django 4.2.6 on 2023-10-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryinvoice',
            name='is_recived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salaryinvoice',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryinvoice',
            name='total_deduct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryinvoice',
            name='total_earn',
            field=models.IntegerField(default=0),
        ),
    ]
