# Generated by Django 4.2.3 on 2023-10-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_switch_employee_uid_delete_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
