# Generated by Django 4.2.3 on 2023-10-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_alter_switch_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='employee',
            new_name='emp',
        ),
    ]
