# Generated by Django 4.2.3 on 2023-10-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0009_alter_employee_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
