# Generated by Django 4.2.3 on 2023-10-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0011_alter_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
