# Generated by Django 4.2.3 on 2023-10-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0013_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
